artifact_location: file:///C:/Users/otloo/OneDrive/%D0%A0%D0%B0%D0%B1%D0%BE%D1%87%D0%B8%D0%B9%20%D1%81%D1%82%D0%BE%D0%BB/neural%20network/course/.laborantum/mlflow_logs/238485478522587542
creation_time: 1783950069131
experiment_id: '238485478522587542'
last_update_time: 1783950069131
lifecycle_stage: active
name: Shallow Feedforward NNs
trace_location: null
workspace: default
