artifact_uri: file:///C:/Users/otloo/OneDrive/%D0%A0%D0%B0%D0%B1%D0%BE%D1%87%D0%B8%D0%B9%20%D1%81%D1%82%D0%BE%D0%BB/neural%20network/course/.laborantum/mlflow_logs/238485478522587542/f6823f6c98b742ce8bec62d1b7d5c9ae/artifacts
end_time: 1783950127670
entry_point_name: ''
experiment_id: '238485478522587542'
lifecycle_stage: active
run_id: f6823f6c98b742ce8bec62d1b7d5c9ae
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1783950077445
status: 3
tags: []
user_id: otloo
